#!/bin/bash
function usage() {
  echo "Usage: kpdf [-p] [-h] [-s] [-c CACHENAME] [-d DPI] <input>"
  echo "-p = show page-by-page output"
  echo "-h = show help"
  echo "-s = strict black-white mode (counts pseudo-BW pages as color)"
  echo "-c = define alternative cache file"
  echo "-d = define alternative DPI (default is 72)"
}

PAGEBYPAGE=0
OUTPUTFILE=".kpdf_cache"
DPI=72
STRICT=0

# READ OPTIONS
while getopts "phc:d:s" opt; do
  case "$opt" in
  p) (( PAGEBYPAGE++ ));;
  s) STRICT=1 ;;
  h) usage && exit 0;;
  c) OUTPUTFILE="$OPTARG";;
  d) DPI="$OPTARG" && echo "Calculating PDF as $DPI dpi";
  esac
done
shift $(( OPTIND - 1 ))

# CHECK FOR INPUT
if [ "$#" -eq 0 ]; then
  echo "Please specify a filename"
  exit 2
fi

MYFILE="$1"
echo "Opening $MYFILE"

# EXECUTE IMAGEMAGICK TO GET PAPER SIZE
identify "$MYFILE" > ${OUTPUTFILE}

# EXECUTE GHOSTSCRIPT TO GET COLORS
gs -q -o - -sDEVICE=inkcov "${MYFILE}" >> ${OUTPUTFILE}

echo "Outputs written to $OUTPUTFILE"

# DECLARE VARS
l=0
IFS=' ' # space is set as delimiter
MYPDF="PDF";
LASTPAGE=0
declare -a PDFINFO

# READ OUTPUT FROM CACHE FILE
while IFS= read -r line
do
  read -ra ADDR <<< "${line/$MYFILE/}" # str is read into an array as tokens separated by IFS
  if [[ ${ADDR[1]} == $MYPDF || ${ADDR[0]} == $MYPDF ]]; then
    # THIS IS PAPER SIZE
    LASTPAGE=$((LASTPAGE+1))
#    echo "Page "$((l))
#    echo "paper="${ADDR[2]}
    if [ ${ADDR[0]} == $MYPDF ]; then
      # ONE PAGE PDF
      W=${ADDR[1]%x*}
      H=${ADDR[1]#*x}
    else
      # MULTIPLE PAGE PDF
      W=${ADDR[2]%x*}
      H=${ADDR[2]#*x}
    fi;
    # CONVERT FROM PT TO INCH TO MM
    W_MM=$(echo "scale=2; ($W/$DPI)*25.4" | bc)
    H_MM=$(echo "scale=2; ($H/$DPI)*25.4" | bc)
#    PDFINFO[$((l))]=${ADDR[2]} # UNCOMMENT FOR INCH
    PDFINFO[$((l))]=$W_MM" x "$H_MM;
  else
    #echo "Page "$((l-LASTPAGE))
    #echo "C="${ADDR[0]}",M="${ADDR[1]}",Y="${ADDR[2]}",K="${ADDR[3]}
    if [[ ${ADDR[0]} == "0.00000" && ${ADDR[1]} == "0.00000" && ${ADDR[2]} == "0.00000" ]]; then
      PDFINFO[$((l-LASTPAGE))]+=" (BW)";
    elif [[ "${ADDR[0]}" == "${ADDR[1]}" && "${ADDR[1]}" == "${ADDR[2]}" && "${ADDR[2]}" == "${ADDR[3]}" ]]; then
      if [ $STRICT ]; then
        PDFINFO[$((l-LASTPAGE))]+=" (COL)";
      else
        PDFINFO[$((l-LASTPAGE))]+=" (Pseudo-BW)";
      fi;
    else
      PDFINFO[$((l-LASTPAGE))]+=" (COL)";
    fi;
  fi
  l=$((l+1))
done < ${OUTPUTFILE}

if [ $PAGEBYPAGE -gt 0 ]; then
  echo "";
  echo "$MYFILE : Overview"
  p=0;
  for i in "${PDFINFO[@]}"
  do
    echo $((p+1)) "=" $i
    p=$((p+1))
  done
fi

echo "";
echo "$MYFILE : Summary"

(IFS=$'\n'; sort <<< "${PDFINFO[*]}") | uniq -c

exit 0
